version: '3'
services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 18080:8089
    volumes:
      - .:/opt/locust
    entrypoint:
      - locust
      - --locustfile
      - locustfile.py
      - --host
      - http://localhost
